apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.admission.certmanager.k8s.io
  labels:
    app: { { include "webhook.name" . } }
    chart: { { include "webhook.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  group: admission.certmanager.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: { { include "webhook.fullname" . } }
    namespace: '{{ .Release.Namespace }}'
  version: v1
